name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  test-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
  
      - name: Build application
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "Building application on $BRANCH_NAME"
          # npm ci
      
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v7.0.0

  
